;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ess-indent-or-complete
	ess-smart-comma
	mouse-drag-vertical-line
	))

(setq mc/cmds-to-run-once
      '(
	cua-set-rectangle-mark
	ess-smart-S-assign
	ess-use-this-dir
	mouse-set-region
	upcase-region
	))
